# Generated by Django 3.0.5 on 2020-10-12 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100)),
                ('bot_tag', models.CharField(default='', max_length=100)),
                ('bot_desc', models.CharField(max_length=1000)),
                ('bot_intents', models.CharField(max_length=256)),
                ('bot_slots', models.CharField(default='none', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Svp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(default='', max_length=1024)),
                ('utterance', models.CharField(default='', max_length=2056, unique=True)),
                ('svp_data', models.CharField(default='', max_length=2056)),
                ('intent', models.CharField(default='none', max_length=50)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_svp', to='api.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=100)),
                ('utterance', models.CharField(max_length=2056, unique=True)),
                ('intent_data', models.CharField(default='', max_length=2056)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='api.Bot')),
            ],
        ),
    ]
