# Generated by Django 3.0.5 on 2020-10-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Va',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('va_name', models.CharField(max_length=100)),
                ('va_tag', models.CharField(default='', max_length=100)),
                ('va_desc', models.CharField(max_length=1000)),
                ('va_intents', models.CharField(max_length=256)),
                ('va_slots', models.CharField(default='none', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Svp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(default='', max_length=1024)),
                ('utterance', models.CharField(default='', max_length=2056, unique=True)),
                ('svp_data', models.CharField(default='', max_length=2056)),
                ('intent', models.CharField(default='none', max_length=50)),
                ('va', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Va')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=100)),
                ('utterance', models.CharField(max_length=2056, unique=True)),
                ('intent_data', models.CharField(default='', max_length=2056)),
                ('va', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Va')),
            ],
        ),
    ]
