# Generated by Django 3.0.4 on 2020-03-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('bot_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bot_desc', models.CharField(max_length=1000)),
                ('bot_skills', models.CharField(max_length=256)),
                ('bot_slots', models.CharField(max_length=500)),
                ('bot_personality', models.CharField(max_length=500)),
                ('bot_personal', models.BooleanField(default=True)),
            ],
        ),
    ]
