# Generated by Django 3.0.4 on 2020-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bot_bot_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_name',
            field=models.CharField(max_length=100),
        ),
    ]
