# Generated by Django 3.0.4 on 2020-03-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200306_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
