# Generated by Django 3.0.5 on 2020-11-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transition',
            old_name='source_va',
            new_name='source_va_id',
        ),
        migrations.AddField(
            model_name='transition',
            name='source_va_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
