# Generated by Django 3.0.4 on 2020-03-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200306_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='bot_id',
        ),
        migrations.AddField(
            model_name='bot',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
