# Generated by Django 3.0.5 on 2020-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201101_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='utterance',
            field=models.CharField(max_length=2056),
        ),
        migrations.AlterField(
            model_name='svp',
            name='utterance',
            field=models.CharField(default='', max_length=2056),
        ),
    ]
