# Generated by Django 3.0.5 on 2020-11-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bls',
            new_name='BlsModel',
        ),
    ]
