# Generated by Django 3.0.4 on 2020-03-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_intent_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='bot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='api.Bot'),
        ),
    ]
