# Generated by Django 3.0.4 on 2020-03-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200308_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svp', models.CharField(max_length=100)),
                ('bot', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bot_svp', to='api.Bot')),
            ],
        ),
    ]
