# Generated by Django 2.2.7 on 2020-05-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200514_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_slots',
            field=models.CharField(db_index=True, default='none', max_length=500),
        ),
    ]
