# Generated by Django 2.2.7 on 2020-05-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200514_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='svp',
            name='intent',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_slots',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
