# Generated by Django 3.0.5 on 2020-05-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200515_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='bot_personal',
        ),
    ]
