# Generated by Django 3.0.5 on 2020-09-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200618_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
