# Generated by Django 3.0.5 on 2020-11-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_responsevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsetemplate',
            name='project',
        ),
    ]
