# Generated by Django 3.0.5 on 2020-11-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_remove_responsetemplate_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetemplate',
            name='device',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
