# Generated by Django 3.0.5 on 2020-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_auto_20201123_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetemplate',
            name='device',
            field=models.CharField(max_length=50),
        ),
    ]
